### ISSUE TITLE
4. Issues for Setting page and Profile pages

### ISSUE THREAD

**Issue by pavankkus** [pfarkya/local-searcher#7]
(1.) in setting page, make all the connection of input with DB.
(2.) Input should be disabled while opening setting, input should be enabled after clicking on edit button. Save button should make all the content again disabled for editing. 
(3.) all the heading of input in setting page should come in line(optional comment).
(4.) About page in profile should be by default clicked. to show the about page content.
(5.) Try to connect all the profile and about page content with DB.

**Comment by pfarkya** [comment]
all work done
