### ISSUE TITLE
4. product page and search page 

### ISSUE THREAD

**Issue by pavankkus** [pfarkya/local-searcher#8]
1.connect product page details with db and make same pages and db for service also.
2. while clicking on add product buttion, edit product page should be empty and while editing product details should be there for referring product.
3. after saving product details page should be redirected to products page only.
4.Edit button on product to be shown to only profile owner only. please check this because we have to keep many things to not to show all.
4. make profiles searchable in search result page.

**Comment by pfarkya** [comment]
all work done closing issue
