### ISSUE TITLE
5.

### ISSUE THREAD

**Issue by pavankkus** [pfarkya/local-searcher#9]
1. save button is not working, if it is saving data then, in products page my saved all products should be refelected, after saving this page should go to view mode. 
2. every time it is automatically redirecting to /app , it should not be automatic it is disturbing work. you have connected it to searchpage although it should go to homepage. i am creating a home page redirect it to that.
3. searchpage showing results of one profile should have ng repeat class for all the searchable results and should redirect to profileview when on click, connect profile view page to a particular search results profile data. 
4. adjust the profileview tabs, width of tabs is not coming properly please adjust it as i am not able to figure it out.

**Comment by pavankkus** [comment]
![image](https://user-images.githubusercontent.com/23234451/54481064-1fd5bf80-4856-11e9-9adc-0676aeb80342.png)
first product not able to edit, it is coming like this only.
either this tab should not be shown.

**Comment by pavankkus** [comment]
![image](https://user-images.githubusercontent.com/23234451/54481099-8ce95500-4856-11e9-92fa-6447b9bd063e.png)
search pr click krne pr sare profiles aa gyi, apne paas profiles kam he isliye sb show kiya  he tune ?

**Comment by pavankkus** [comment]
![image](https://user-images.githubusercontent.com/23234451/54481127-e5b8ed80-4856-11e9-925f-1d5a37819ef7.png)
after clicking on any profile 
the resulted profile should show all the details of clicked profile

**Comment by pavankkus** [comment]
if i am going to my profile from search results it is not showing my details
my profile details , my product details etc

**Comment by pavankkus** [comment]
![image](https://user-images.githubusercontent.com/23234451/54481980-1e11f900-4862-11e9-9878-19e2f3ad27b9.png)

i have added a profile photo or logo uploading location so that any one will update his profile logo from setting 

please add photo technology also in this project 
how we will be saving a photo by reducing its size or compressing 
please make it usable so that we can update our profile photos
and reflect this photo on profile also

**Comment by pfarkya** [comment]
All work done closing issue
